name: school_bus_tracker
description: A school bus tracking application for drivers and parents/students.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.2.0
  firebase_database: ^12.1.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  
  # Fonts
  google_fonts: ^6.3.2
  
  # Maps
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  
  # Location
  geolocator: ^13.0.1
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true